#
# step V.b
# Install and configure Consul (backend datastore) on all hypervisors
#

- hosts: lightcrest
  tasks:
    - name: consul install
      apt:
        name: consul
        state: latest
    - name: kahu-powertrain KAHU_REST_OPTIONS to listen on 0.0.0.0 
      copy:
        src: ./consul-20-agent.json
        dest:  /etc/consul.d/20-agent.json 
