#
# step V.a.2
# Install and Configure Kahu packages on all hypervisors
#
    - name: kahu-powertrain apt source
      copy:
        src: ./kahu-powertrain.list
        dest:  /etc/apt/sources.list.d/kahu-powertrain.list
    - name: apt-get update
      shell: apt-get update --allow-insecure-repositories
      args:
        warn: false
      register: apt_status
      ignore_errors: true
    - name: deal with older versions of apt-get
      shell: apt-get update
      args:
        warn: false
      when: apt_status.rc != 0
    - name: apt update_cache
      apt:
        force: yes
        update_cache: yes
    - name: apt-transport-https
      apt:
        force: yes
        name: apt-transport-https
        state: latest
    - name: powertrain
      apt:
        name: kahu-powertrain
        state: latest
    - name: nginx
      apt:
        force: yes
        name: nginx
        state: latest
    - name: ssl-cert
      apt:
        force: yes
        name: ssl-cert
        state: latest
    - name: jq
      apt:
        force: yes
        name: jq
        state: latest
    - name: curl
      apt:
        force: yes
        name: curl
        state: latest
    - name: wget
      apt:
        force: yes
        name: wget
        state: latest
    - name: rsync
      apt:
        force: yes
        name: rsync
        state: latest
    - name: htop
      apt:
        force: yes
        name: htop
        state: latest
#
# V.a.2
# Edit /etc/default/kahu-powertrain to listen on 0.0.0.0 or appropriate IP as required
# Make a backup.
#
    - name: kahu-powertrain KAHU_REST_OPTIONS to listen on 0.0.0.0 
      lineinfile:
        dest: /etc/default/kahu-powertrain
        regexp: '^KAHU_REST_OPTIONS='
        line: KAHU_REST_OPTIONS="-a 0.0.0.0:8080 -c /kahu/etc/rest.toml"
        backup: yes
    - name: kahu-powertrain KAHU_HV_OPTIONS to listen on 0.0.0.0 
      lineinfile:
        dest: /etc/default/kahu-powertrain
        regexp: '^KAHU_HV_OPTIONS='
        line: KAHU_HV_OPTIONS="-a 0.0.0.0:8999 -c /kahu/etc/hv.toml"
        backup: yes

