#
# step V.a
# Configure remote access
# a) ssh 
# b) ipmi
#

- name: consul install
  apt:
    name: consul
    state: latest
- name: Create consul directory 
  file:
    path: /var/lib/consul
    state: directory
    owner: consul
    group: consul
- name: start consul
  service:
    name: consul
    state: started
- name: kahu-powertrain KAHU_REST_OPTIONS to listen on 0.0.0.0 
  copy:
    src: ./consul-20-agent.json
    dest:  /etc/consul.d/20-agent.json 
- name: replace retry_join ip addresses
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"retry_join'
    line: '"retry_join": [ {{ var_consul_retry_join }} ],'
- name: replace advertise_addr ip addresses
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"advertise_addr'
    line: '"advertise_addr":  "{{ ansible_default_ipv4.address }}" ,'
- name: replace bootstrap expect count if only 1 node
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"bootstrap_expect'
    line: '"bootstrap":  true ,'
  when: var_bootstrap_expect == 1
- name: replace bootstrap expect count if more than 1 node
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"bootstrap_expect'
    line: '"bootstrap_expect":  {{ var_bootstrap_expect }} ,'
  when: var_bootstrap_expect != 1
- name: replace node name
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"node_name'
    line: '"node_name":  "{{ var_consul_node + "-" + ansible_default_ipv4.address }}" ,'
- name: replace advertise_addr ip addresses
  lineinfile:
    dest: /etc/consul.d/20-agent.json
    regexp: '\"datacenter'
    line: '"datacenter":  "{{ var_consul_datacenter }}" ,'
- name: nginx configuration
  copy:
    src: ./nginx-config
    dest:  /etc/nginx/sites-enabled/default
